import streamlit as st
from rag_pipeline import process_document
from agents import retrieve_docs, generate_answer, reflect_answer

st.set_page_config(page_title="RAG Document QA", layout="wide")

st.title("📄 AI Document Q&A")
st.caption("Upload a document and ask questions using Retrieval Augmented Generation.")

uploaded_file = st.file_uploader("📤 Upload a PDF")

if uploaded_file:

    st.markdown("### ⚙ Processing Document")

    with st.spinner("Chunking and embedding document..."):
        retriever, chunks = process_document(uploaded_file)

    st.success(f"✅ Document processed successfully")
    
    col1, col2 = st.columns(2)

    with col1:
        st.markdown("### 📊 Pipeline Info")
        st.markdown("**Embedding Model:** `all-MiniLM-L6-v2`")
        st.markdown("**Vector Store:** `FAISS`")
        st.markdown(f"**Total Chunks Created:** `{len(chunks)}`")

    with col2:
        st.markdown("### 📄 Preview")
        st.code(chunks[0].page_content[:500])

    st.divider()

    question = st.text_input("💬 Ask a question about the document")

    if question:

        state = {
            "question": question,
            "retriever": retriever
        }

        colA, colB = st.columns(2)

        # ---------- LEFT COLUMN ----------
        with colA:

            st.markdown("### 🔎 Retrieval Step")

            with st.spinner("🔎 Searching document embeddings..."):
                state = retrieve_docs(state)

            st.success("Relevant chunks retrieved")

            with st.expander("View Retrieved Chunks"):
                for i, doc in enumerate(state["docs"]):
                    st.markdown(f"**Chunk {i+1}**")
                    st.write(doc.page_content)

            with st.expander("View Retrieved Context"):
                st.write(state["context"])

        # ---------- RIGHT COLUMN ----------
        with colB:

            st.markdown("### 🤖 Generation Step")

            with st.spinner("🤖 Generating answer using Mixtral..."):
                state = generate_answer(state)

            st.info("Initial answer generated by the model")

            with st.expander("View Initial Answer"):
                st.write(state["answer"])

            st.markdown("### 🧠 Reflection Step")

            with st.spinner("🧠 Verifying and refining answer..."):
                state = reflect_answer(state)

            st.success("Answer verified and refined")

        st.divider()

        st.markdown("### ✨ Final Answer")

        st.markdown(
            f"""
            <div style="
            padding:20px;
            border-radius:10px;
            background-color:#f6faff;
            border:1px solid #d6e4ff;
            font-size:18px;
            color:black;">
            {state["final_answer"]}
            </div>
            """,
            unsafe_allow_html=True
        )

        st.markdown("### ⚙ Agent Workflow")

        st.markdown(
            """
            🟢 **Retriever Agent** →  
            🔵 **Generator Agent** →  
            🟣 **Reflection Agent**
            """
        )